## A) Analyzing Thanksgiving Dinner 2015 - Unit 2 

The dataset is stored in the csv called thanksgiving.csv
https://github.com/fivethirtyeight/data/tree/master/thanksgiving-2015

### About the Data
Using a SurveyMonkey poll, we asked 1,058 respondents on Nov. 17, 2015 the following questions about their Thanksgiving:
The dataset has 65 columns, and 1058 rows. Most of the column names are questions,and most of the column values are string responses to the questions. 

Most of the columns are categorical, as a survey respondent had to select one of a few options.For example, one of the first  column names is What is typically the main dish at your Thanksgiving dinner?. The potential responses are:

+ Turkey
+ Other (please specify)
+ Ham/Pork
+ Tofurkey
+ Chicken
+ Roast beef
+ I don't know
+ Turducken

Most of the columns follow the same question/response format as the above.  
There are also quite a few NaN values in the columns, which occurred when a survey respondent didn't fill out a question   because they didn't want to, or it didn't apply to them.

1. Do you celebrate Thanksgiving? --  a Yes/No reponse to the question
2. What is typically the main dish at your Thanksgiving dinner?
   Other (please specify)
3. How is the main dish typically cooked?
   Other (please specify)
4. What kind of stuffing/dressing do you typically have?
   Other (please specify)
5. What type of cranberry sauce do you typically have? 
   Other (please specify)
6. Do you typically have gravy?
7. Which of these side dishes are typically served at your Thanksgiving dinner? Please select all that apply.
   + Brussel sprouts
   + Carrots
   + Cauliflower
   + Corn
   + Cornbread
   + Fruit salad
   + Green beans/green bean casserole
   + Macaroni and cheese
   + Mashed potatoes
   + Rolls/biscuits
   + Vegetable salad
   + Yams/sweet potato casserole
   + Other (please specify)
8. Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. 
   + Apple
   + Buttermilk
   + Cherry
   + Chocolate
   + Coconut cream
   + Key lime
   + Peach
   + Pecan
   + Pumpkin
   + Sweet Potato
   + None 
   + Other (please specify)
9. Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.
   + Apple cobbler
   + Blondies
   + Brownies
   + Carrot cake
   + Cheesecake
   + Cookies
   + Fudge
   + Ice cream
   + Peach cobbler
   + None
   + Other (please specify)
10. Do you typically pray before or after the Thanksgiving meal?
11. How far will you travel for Thanksgiving?
12. Will you watch any of the following programs on Thanksgiving? Please select all that apply. 
    + Macy's Parade
13. What's the age cutoff at your "kids' table" at Thanksgiving?
14. Have you ever tried to meet up with hometown friends on Thanksgiving night?
15. Have you ever attended a "Friendsgiving?"
16. Will you shop any Black Friday sales on Thanksgiving Day?
17. Do you work in retail?
18. Will you employer make you work on Black Friday?
19. How would you describe where you live? -- responses are Suburban, Urban, and Rural.
20. Age -- resposes are one of several categories, such as 18-29, and 30-44.
21. What is your gender?
23. How much total combined money did all members of your HOUSEHOLD earn last year? such as $75,000 to $99,999.
24. US Region

Most of the columns follow the same question/response format as the above.  
There are also quite a few NaN values in the columns, which occurred when a survey respondent didn't fill out a question because they didn't want to, or it didn't apply to them.

## B) Processing the Data 

+ Import the pandas package.
+ Use the pandas.read_csv() function to read the thanksgiving.csv file in.
+ Make sure to specify the keyword argument encoding="Latin-1", as the CSV file isn't encoded normally.
+ Assign the result to the variable data.
+ Display the first few rows of data to see what the columns and rows look like.
+ In a separate notebook cell, display all of the column names to get a sense of what the data consists of.
+ You can use the pandas.DataFrame.columns property to display the column names.

In [1]:
import pandas as pd 
data = pd.read_csv("thanksgiving.csv",encoding="Latin-1")
data.head(4)

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific

## B) Column Information 
In a separate notebook cell, display all of the column names to get a sense of what the data consists of.
You can use the pandas.DataFrame.columns property to display the column names.

In [2]:
print(data.columns)

Index(['RespondentID', 'Do you celebrate Thanksgiving?',
       'What is typically the main dish at your Thanksgiving dinner?',
       'What is typically the main dish at your Thanksgiving dinner? - Other (please specify)',
       'How is the main dish typically cooked?',
       'How is the main dish typically cooked? - Other (please specify)',
       'What kind of stuffing/dressing do you typically have?',
       'What kind of stuffing/dressing do you typically have? - Other (please specify)',
       'What type of cranberry saucedo you typically have?',
       'What type of cranberry saucedo you typically have? - Other (please specify)',
       'Do you typically have gravy?',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Brussel sprouts',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Carrots',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cauliflower',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Corn',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cornbread',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Fruit salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Green beans/green bean casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Macaroni and cheese',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Mashed potatoes',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Rolls/biscuits',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Squash',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Vegetable salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Yams/sweet potato casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Buttermilk',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Cherry',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Chocolate',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Coconut cream',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Key lime',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Peach',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Sweet Potato',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - None',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Apple cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Blondies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Brownies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Carrot cake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cheesecake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cookies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Fudge',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Ice cream',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Peach cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - None',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify)',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify).1',
       'Do you typically pray before or after the Thanksgiving meal?',
       'How far will you travel for Thanksgiving?',
       'Will you watch any of the following programs on Thanksgiving? Please select all that apply. - Macy's Parade',
       'What's the age cutoff at your "kids' table" at Thanksgiving?',
       'Have you ever tried to meet up with hometown friends on Thanksgiving night?',
       'Have you ever attended a "Friendsgiving?"',
       'Will you shop any Black Friday sales on Thanksgiving Day?',
       'Do you work in retail?',
       'Will you employer make you work on Black Friday?',
       'How would you describe where you live?', 'Age', 'What is your gender?',
       'How much total combined money did all members of your HOUSEHOLD earn last year?',
       'US Region'],
      dtype='object')

## C) Filtering Out Rows With Data From the  DataFrame

Because we want to understand what people ate for Thanksgiving, we'll remove any responses from people who don't celebrate it.      
The column **Do you celebrate Thanksgiving?** contains this information. We only want to keep data for people who answered Yes to this questions.

+ Use the pandas.Series.value_counts() method to display counts of how many times each category occurs in the  
  **Do you celebrate Thanksgiving?** column.

In [3]:
print(data['Do you celebrate Thanksgiving?'].value_counts())

Yes    980
No      78
Name: Do you celebrate Thanksgiving?, dtype: int64

Filter out any rows in data where the response to Do you celebrate Thanksgiving? is not Yes.  
At the end, all of the values in the **Do you celebrate Thanksgiving?** column of data should be Yes.

In [4]:
# Filter out rows with yes 
yes_df = data[data['Do you celebrate Thanksgiving?'] =='Yes']
yes_df.head(5)

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific

## D)  Using value_counts To Explore Main Dishes

Let's explore what main dishes people tend to eat during Thanksgiving dinner.  
We can again use the value_counts method to help us with this.

+ Use the pandas.Series.value_counts() method to display counts of how many times each category occurs in the
  ** What is typically the main dish at your Thanksgiving dinner?** column.

In [5]:
yes_df['What is typically the main dish at your Thanksgiving dinner?'].value_counts()

Turkey                    859
Other (please specify)     35
Ham/Pork                   29
Tofurkey                   20
Chicken                    12
Roast beef                 11
I don't know                5
Turducken                   3
Name: What is typically the main dish at your Thanksgiving dinner?, dtype: int64

+ Display the **Do you typically have gravy?** column for any rows from data where the 
  **What is typically the main dish at your Thanksgiving dinner?** column equals Tofurkey.
+ Select the **Do you typically have gravy?** column, and display it.

In [6]:
gravy_df = data[data['What is typically the main dish at your Thanksgiving dinner?'] == 'Tofurkey']
gravy_df['Do you typically have gravy?']

4      Yes
33     Yes
69      No
72      No
77     Yes
145    Yes
175    Yes
218     No
243    Yes
275     No
393    Yes
399    Yes
571    Yes
594    Yes
628     No
774     No
820     No
837    Yes
860     No
953    Yes
Name: Do you typically have gravy?, dtype: object

## E) Figuring Out What Pies People Eat

Now that we've looked into the main dishes, let's explore the dessert dishes. Specifically, we'll look at how many people eat Apple, Pecan, or Pumpkin pie during Thanksgiving dinner. This data is encoded in the following three columns:

+ Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple
+ Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin
+ Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan

In all three columns, the value is either the name of the pie if the person eats it for Thanksgiving dinner, or null otherwise.  We can find out how many people eat one of these three pies for Thanksgiving dinner by figuring out for how many people all three columns are null.

+ You may recall from an earlier mission that the **pandas.isnull()** function will return a Boolean Series indicating whether or not each value in a specified DataFrame or Series is null.

We can also use the & operator to combine two Boolean Series into a single one.  
If both Series contain True in a position, the result will be True. Otherwise, the result will be False. 

If we use the **pandas.isnull()** function to check where all three columns are null, then use the & operator to join all of the Series, we'll end up with a single Boolean Series. Where that Series contains False, the person ate at least one of the types of pies for Thanksgiving dinner. Where it contains True, they ate none of the types of pies.

+ Generate a Boolean Series indicating where the **Which type of pie is typically served at your Thanksgiving dinner? Please      select all that apply. - Apple** column is null. Assign to the apple_isnull variable.
+ Generate a Boolean Series indicating where the **Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin** column is null. Assign to the pumpkin_isnull variable.
+ Generate a Boolean Series indicating where the **Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan** column is null. Assign to the pecan_isnull variable.
+ Join all three Series using the & operator, and assign the result to no_pies.
+ Display the unique values and how many times each occurs in the no_pies column.

In [7]:
apple_isnull = data['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple'] ==""
pumpkin_isnull = data['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin'] ==""
pecan_isnull = data['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan'] == ""
ate_pies = apple_isnull&pumpkin_isnull&pecan_isnull 


ate_pies.value_counts()

False    1058
dtype: int64

## F) Converting Age To Numeric

Let's analyze the Age column in more depth. In order to analyze the Age column, we'll first need to convert it to numeric values. This will make it simple to figure out things like the average age of survey respondents. The Age column contains   values that fall into one of a few categories:

+ 18 - 29
+ 30 - 44
+ 45 - 59
+ 60+
+ null

Because we're missing the exact age value, we won't be able to extract an exact integer value,  
and we'll instead have to extract the first age value in the strings given.
 
We can do this by splitting each value on the space character (), then taking the first item in the resulting list.  
We'll also have to replace the + character to account for 60+, which follows a different format than the rest.

+ Write a function to convert a single string to an appropriate integer value. 
  This will allow us to convert the values in the Age column to integers.
+ Use the isnull() function to check if the value is null. If it is, return None.
  Use the isnull() function to check if the value is null. If it is, return None.
+ Replace the + character in the result with an empty string to remove it.
  Use int() to convert the result to an integer.
+ Return the result.
+ Use the **pandas.Series.apply()** method to apply the function to each value in the Age column of data.  
  Assign the result to the int_age column of data.
+ Call the pandas.Series.describe() method on the int_age column of data, and display the result.
+ In a separate markdown cell, write up your findings.  
  Is there anything that we should be aware of about the results or our methodology?  
  Is this a true depiction of the ages of survey participants?

In [8]:
def strtoint(row):
    ageclass = row['Age']
    if pd.isnull(ageclass):
        return None 
    elif ageclass.endswith('+'):
        return int(ageclass.strip('+'))  
    else:
        y = ageclass.split(" ")
        return int(y[0])  

data['int_age']=  data.apply(strtoint,axis=1)   
print(data['int_age'])


data['int_age'].describe()

0       18.0
1       18.0
2       18.0
3       30.0
4       30.0
5       18.0
6       18.0
7       18.0
8       30.0
9       30.0
10      30.0
11      30.0
12      18.0
13      18.0
14      60.0
15      30.0
16      30.0
17      18.0
18      30.0
19      30.0
20      30.0
21      18.0
22      18.0
23      18.0
24      30.0
25      18.0
26      30.0
27      18.0
28      30.0
29      30.0
        ...
1028    60.0
1029    60.0
1030    45.0
1031    45.0
1032    18.0
1033    30.0
1034    30.0
1035    30.0
1036    30.0
1037    30.0
1038    60.0
1039    18.0
1040    30.0
1041    45.0
1042    45.0
1043    45.0
1044    60.0
1045    30.0
1046    18.0
1047    30.0
1048    60.0
1049     NaN
1050    60.0
1051    60.0
1052    18.0
1053    30.0
1054    60.0
1055    60.0
1056     NaN
1057     NaN
Name: int_age, Length: 1058, dtype: float64

count    1025.000000
mean       39.383415
std        15.398493
min        18.000000
25%        30.000000
50%        45.000000
75%        60.000000
max        60.000000
Name: int_age, dtype: float64

## I) Converting Income To Numeric

The **How much total combined money did all members of your HOUSEHOLD earn last year?** column is very similar to the Age column.It contains categories, but can be converted to numerical values. Here are the unique values in the column:

+ Prefer not to answer
+ $0 to $9,999
+ $10,000 to $24,999
+ $25,000 to $49,999
+ $50,000 to $74,999
+ $75,000 to $99,999
+ $100,000 to $124,999
+ $125,000 to $149,999
+ $150,000 to $174,999
+ $175,000 to $199,999
+ $200,000 and up
+ null


We can convert these values to numeric by again splitting on the space character ().  
We'll then have to account for the string Prefer.  
Finally, we'll be able to replace the dollar sign character $ and the comma ,, and return the result.

+ Write a function to convert a single string to an appropriate integer income value.
  Use the isnull() function to check if the value is null. If it is, return None.
+ Split the string on the space character (), and extract the first item of the resulting list.
  If the result equals Prefer, return None.
+ Replace the $ and , characters in the result with empty strings to remove them.
+ Use int() to convert the result to an integer.
+ Return the result.
+ Use the **pandas.Series.apply()** method to apply the function to each value in the **How much total combined money did all members of your HOUSEHOLD earn last year?** column of data.
+ Assign the result to the int_income column of data.
+ Call the **pandas.Series.describe()** method on the int_income column of data, and display the result.
  In a separate markdown cell, write up your findings.
+ Is there anything that we should be aware of about the results or our methodology?
+ Is this a true depiction of the incomes of survey participants?

In [9]:
def incometonumeric(row):
    money_earned = row['How much total combined money did all members of your HOUSEHOLD earn last year?']
    
    if pd.isnull(money_earned):
        return None 
    else:
        y = money_earned.split(" ")
        if y[0] == 'Prefer':
            return None 
        else:
            income_earned = list(y[0])
            char_remove = ['$',',']
            
            new_income = ''.join(l for l in income_earned if not l in char_remove)
            return int(new_income)       
            
data['int_income'] = data.apply(incometonumeric,axis=1)   
print(data['int_income'])

data['int_income'].describe()

0        75000.0
1        50000.0
2            0.0
3       200000.0
4       100000.0
5            0.0
6        25000.0
7            NaN
8        75000.0
9        25000.0
10       25000.0
11       25000.0
12           0.0
13           0.0
14       50000.0
15      200000.0
16      200000.0
17       75000.0
18       25000.0
19       75000.0
20       75000.0
21           0.0
22           0.0
23           0.0
24       50000.0
25      200000.0
26       50000.0
27      100000.0
28           NaN
29       75000.0
          ...
1028         NaN
1029     50000.0
1030     10000.0
1031     75000.0
1032         NaN
1033     75000.0
1034         NaN
1035     25000.0
1036     50000.0
1037     10000.0
1038    100000.0
1039     75000.0
1040     50000.0
1041     25000.0
1042    125000.0
1043     75000.0
1044     25000.0
1045     75000.0
1046     10000.0
1047     25000.0
1048     75000.0
1049         NaN
1050    125000.0
1051    125000.0
1052         0.0
1053    100000.0
1054     50000.0
1055    100000.0
1056         NaN
1057         NaN
Name: int_income, Length: 1058, dtype: float64

count       889.000000
mean      74077.615298
std       59360.742902
min           0.000000
25%       25000.000000
50%       50000.000000
75%      100000.000000
max      200000.000000
Name: int_income, dtype: float64

## J) Correlating Travel Distance And Income

We can now see how the distance someone travels for Thanksgiving dinner relates to their income level. It's safe to hypothesize that people earning less money could be younger, and would travel to their parent's houses for Thanksgiving. People earning more are more likely to have Thanksgiving at their house as a result.

We can test this by filtering data based on int_income, and seeing what the values in the **How far will you travel for Thanksgiving?** column are.

+ See how far people earning under 150000 will travel.
  Filter data, and only select rows where int_income is less than 150000.
+ Use indexing to select the How far will you travel for Thanksgiving? column.
+ Use the value_counts() method to count up how many times each value occurs in the column.
  Display the results.

In [10]:
#check distance travelled by under $15,000
under_150000 = data['int_income'] < 150000
under_150000_values = data[under_150000]
under_150000_values.describe()

       RespondentID     int_age     int_income
count  7.420000e+02  742.000000     742.000000
mean   4.336735e+09   38.951482   52735.849057
std    5.013050e+05   15.424285   37046.788566
min    4.335943e+09   18.000000       0.000000
25%    4.336335e+09   30.000000   25000.000000
50%    4.336800e+09   45.000000   50000.000000
75%    4.337043e+09   60.000000   75000.000000
max    4.337955e+09   60.000000  125000.000000

In [11]:
travel_under150= under_150000_values['How far will you travel for Thanksgiving?']
travel_under150.value_counts()

Thanksgiving is happening at my home--I won't travel at all                         281
Thanksgiving is local--it will take place in the town I live in                     203
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    150
Thanksgiving is out of town and far away--I have to drive several hours or fly       55
Name: How far will you travel for Thanksgiving?, dtype: int64

+ Filter data, and only select rows where int_income is greater than 150000.
+ Use indexing to select the How far will you travel for Thanksgiving? column.
+ Use the value_counts() method to count up how many times each value occurs in the column.
  Display the results
+ Write up your findings in a markdown cell.
+ See how far people earning over 150000 will travel.

In [12]:
over_150000 = data['int_income'] > 150000
over_150000_values = data[over_150000]
over_150000_values.describe()

       RespondentID     int_age     int_income
count  1.070000e+02  107.000000     107.000000
mean   4.336793e+09   46.317757  193691.588785
std    4.597716e+05   12.855216   10909.932479
min    4.335957e+09   18.000000  175000.000000
25%    4.336528e+09   45.000000  187500.000000
50%    4.336830e+09   45.000000  200000.000000
75%    4.337003e+09   60.000000  200000.000000
max    4.337933e+09   60.000000  200000.000000

In [13]:
#check distance travelled by oover $150,000 earners
travel_over150= over_150000_values['How far will you travel for Thanksgiving?']
travel_over150.value_counts()

Thanksgiving is happening at my home--I won't travel at all                         49
Thanksgiving is local--it will take place in the town I live in                     25
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    16
Thanksgiving is out of town and far away--I have to drive several hours or fly      12
Name: How far will you travel for Thanksgiving?, dtype: int64

## K)Linking Friendship And Age

There are two columns which directly pertain to friendship, **Have you ever tried to meet up with hometown friends on Thanksgiving night?**, and **Have you ever attended a "Friendsgiving?".** In the US, a "Friendsgiving" is when instead of  traveling home for the holiday, you celebrate it with friends who live in your area.  
Both questions seem skewed towards younger people. Let's see if this hypothesis holds up.

In order to see the average ages of people who have done both, we can use a pivot table.  
As you may recall from an earlier mission, we can generate a pivot table with the **pandas.DataFrame.pivot_table()** method.  
By calling this method on data, and passing in the right keyword arguments, we can generate a table showing the average ages of  people who answered Yes to both questions, answered Yes to one question, and so on.

+ Generate a pivot table showing the average age of respondents for each category of **Have you ever tried to meet up with      hometown friends on Thanksgiving night?** and **Have you ever attended a "Friendsgiving?"**.
+ Call the pivot_table() method on data.
+ Pass in **"Have you ever tried to meet up with hometown friends on Thanksgiving night?"** to the index keyword argument.
+ Pass in **'Have you ever attended a "Friendsgiving?"'** to the columns keyword argument.
+ Pass in **"int_age"** to the values keyword argument.
+ Display the results.
+ Generate a pivot table showing the average income of respondents for each category of **Have you ever tried to meet up with hometown friends on Thanksgiving night?** and **Have you ever attended a "Friendsgiving?".**
+ Write up a markdown cell with your findings.

### Pivot table Setup 
+ format: pd.pivot_table(df,index=["Name"])

http://pbpython.com/pandas-pivot-table-explained.html

In [14]:

results = data.pivot_table(index="Have you ever tried to meet up with hometown friends on Thanksgiving night?",columns='Have you ever attended a "Friendsgiving?"',
                            values='int_age')
results

Have you ever attended a "Friendsgiving?"                  No        Yes
Have you ever tried to meet up with hometown fr...
No                                                  42.283702  37.010526
Yes                                                 41.475410  33.976744

+ Generate a pivot table showing the average income of respondents for each category of **Have you ever tried to meet up with hometown friends on Thanksgiving night?** and **Have you ever attended a "Friendsgiving?".**
+ Write up a markdown cell with your findings.

In [15]:
results_income = data.pivot_table(index="Have you ever tried to meet up with hometown friends on Thanksgiving night?",columns='Have you ever attended a "Friendsgiving?"',
                            values= 'int_income')
results_income

Have you ever attended a "Friendsgiving?"                     No           Yes
Have you ever tried to meet up with hometown fr...
No                                                  78914.549654  72894.736842
Yes                                                 78750.000000  66019.736842

## Here are some potential next steps:

+ Figure out the most common dessert people eat.
+ Figure out the most common complete meal people eat.
+ Identify how many people work on Thanksgiving.
+ Find regional patterns in the dinner menus.
+ Find age, gender, and income based patterns in dinner menus.

In [16]:
data['Will you employer make you work on Black Friday?'].value_counts()

Yes              43
No               20
Doesn't apply     7
Name: Will you employer make you work on Black Friday?, dtype: int64